# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Features
    url: /#features
    weight: 20
  - name: Solutions
    url: /#solutions
    weight: 30
  - name: Data Description
    url: 
    weight: 60
  - name: County
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: Quick Download
    url: 
    weight: 70
  - name: County .csv
    url: "/uploads/county_carr_public_09132024.csv"
    weight: 70
    parent: Quick Download
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
