# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Team
    url: /people
    weight: 20
  - name: Solutions
    url: /#solutions
    weight: 30
  - name: Data Description
    url: 
    weight: 60
  - name: County
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: Schools
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: ZIP Codes
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: Tribal
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: Tracts
    url: "/doc/SchoolDistrictCarr.html"
    weight: 60
    parent: Data Description
  - name: Quick Download
    url: 
    weight: 70
  - name: County .csv
    url: "/doc/county_carr_public_09132024.csv"
    weight: 70
    parent: Quick Download
  - name: Schools .csv
    url: "/doc/county_carr_public_09132024.csv"
    weight: 70
    parent: Quick Download
  - name: ZIP codes .csv
    url: "/doc/county_carr_public_09132024.csv"
    weight: 70
    parent: Quick Download
  - name: Tribal .csv
    url: "/doc/county_carr_public_09132024.csv"
    weight: 70
    parent: Quick Download
  - name: Tracts .csv
    url: "https://zenodo.org/records/8072187/files/carr_public_v1.csv?download=1"
    weight: 70
    parent: Quick Download
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
